# Generated by Django 5.2.8 on 2025-11-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="colection",
            new_name="collection",
        ),
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
